### ISSUE TITLE
Menu functionality at mobiles

### ISSUE THREAD

**Issue by SonataAmanes** [woocommerce/storefront#860] opened 2018-05-09 12:28 UTC
Hello,
The following issue applies at mobile:

On previous version, the menu was expanded by default, showing every submenu.
At the current update 2.3.0, I notice that the menu is retracted by default, with no option to view the submenu.

Ideally, the menu should be retracted by default, but the submenu should be viewable on ckick.
However, between the two options, it is much preferable to have the menu expanded by default.

I am using max mega menu, I don't know if this has something to do.

Thanks

**Comment by tiagonoronha** [comment] 2018-05-09 14:05
Hi @SonataAmanes!

This is how the handheld menu should look like after the update to 2.3:

![screen shot 2018-05-09 at 15 03 28](https://user-images.githubusercontent.com/1177726/39819019-3f01af24-539a-11e8-995c-c24ac066b5b7.png)

and when you click the arrow:

![screen shot 2018-05-09 at 15 04 35](https://user-images.githubusercontent.com/1177726/39819050-59c2cff0-539a-11e8-8283-ee77e6a009f7.png)

If you cannot see the arrow, you'll probably experiencing [this issue](https://github.com/woocommerce/storefront/issues/855). A fix will be available soon.

**Comment by SonataAmanes** [comment] 2018-05-09 14:47
Hi Tiago,
Thanks for your immediate reply.
You are correct, the functionality is here, but the arrows are invisible.
Will this be fixed at 2.3.1?
Regards,
Kostas

**Comment by tiagonoronha** [comment] 2018-05-09 16:31
Yes, 2.3.1 will be available very soon!

Closing this issue as it is a duplicate of #853.

**Closed by tiagonoronha** 2018-05-09 16:31 UTC
Labels: Status: Needs Author Feedback

**Comment by SonataAmanes** [comment] 2018-05-09 16:33
Many thanks!
