### ISSUE TITLE
Stripe credit card icons look cramped in Storefront checkout (shortcode)

### ISSUE THREAD

**Issue by haszari** [woocommerce/storefront#1342] opened 2020-05-07 02:38 UTC
## Describe the bug
The Stripe payment gateway extension shows some payment card icons in the checkout payment area.  In storefront these look a little cramped; they wrap on to another line, and there's no padding in the container. 

This seems to be a Storefront specific issue as the icons look good in various other themes (Twenty Twenty, Twenty Nineteen etc). Stripe is a very popular payment extension and is recommended as a default payment gateway in Woo onboarding. 

It may be that this issue should be fixed in Stripe plugin. For example, if it affects any theme that causes the icons to wrap.

Note - this affects traditional shortcode checkout, not the checkout block (currently in development).

- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## Screenshots
Storefront - cramped:
<img width="543" alt="Screen Shot 2020-05-07 at 2 35 13 PM" src="https://user-images.githubusercontent.com/4167300/81248218-f9816d80-906f-11ea-9131-9e01834cb8d1.png">

Twenty Twenty - good:
<img width="680" alt="Screen Shot 2020-05-07 at 2 26 23 PM" src="https://user-images.githubusercontent.com/4167300/81248052-a3142f00-906f-11ea-948b-c20aaf6cc9d9.png">

## To Reproduce
1. Set up a Woo store with [Stripe plugin](https://wordpress.org/plugins/woocommerce-gateway-stripe/) installed and configured to accept credit cards.
2. Add stuff to cart and view (shortcode) checkout.
4. Look at the credit card icons - they are tightly packed around the radio button text and hard up against the bottom edge of grey box.

## Expected behavior
Nice looking icons on all screens/window sizes.

### Browser Environment

- Platform: macOS
- Browser(s): Chrome

**Comment by haszari** [comment] 2020-05-13 02:50
Added to 2.5.7 (assuming this is easy/low risk) - Stripe is a very popular payment extension, the card icons should look good in checkout.

**Comment by nielslange** [comment] 2020-05-13 18:04
@haszari Based on your screenshot, it looks like the card icons are distributed over two rows, as the checkout still contains the sidebar. Don't you think that https://github.com/woocommerce/storefront/issues/1349 would solve this credit card display issue?

**Comment by haszari** [comment] 2020-05-13 20:50
> Based on your screenshot, it looks like the card icons are distributed over two rows, as the checkout still contains the sidebar. Don't you think that #1349 would solve this credit card display issue?

Good point @nielslange  - using a full width template (layout) would definitely mitigate this. There's still an issue with smaller screens, but maybe this is lower priority than I originally thought.

**Comment by nielslange** [comment] 2020-05-14 05:51
@haszari I also looked up the HTML structure of the card icons to see if it's possible to move the card icons into the next row. The current HTML structure would not allow such a change, but I'll look up this issue later tonight to look for options.

**Comment by haszari** [comment] 2020-05-14 20:08
We could also potentially reduce the number of icons as the div gets smaller, responsive style.

**Comment by nielslange** [comment] 2020-05-18 04:17
> We could also potentially reduce the number of icons as the div gets smaller, responsive style.

I looked up this issue again and it seems that the card icons are bigger on Storefront than on other themes. I'd reduce the size to see if that already solves the issue.

**Comment by Aljullu** [comment] 2020-10-16 12:17
I was reviewing #1468 from @nielslange, while it looks good, I'm not sure this is something that has to be fixed in Storefront, I could reproduce the issue in other themes as well.

For example, these screenshots are on mobile (viewport width of 350px):

_Twenty Twenty:_
![imatge](https://user-images.githubusercontent.com/3616980/96256888-bb428f80-0fb9-11eb-811b-9b6e611a93c3.png)

_Twenty Nineteen:_
![imatge](https://user-images.githubusercontent.com/3616980/96256968-dca37b80-0fb9-11eb-9998-bd7da2b0bad9.png)

_Ocean WP:_
![imatge](https://user-images.githubusercontent.com/3616980/96257037-fe046780-0fb9-11eb-9f28-85b54a7acac3.png)

In my opinion, this seems to be a styling issue in Stripe not specific to Storefront.

Thoughts @nielslange @haszari?

**Comment by haszari** [comment] 2020-10-18 19:46
> In my opinion, this seems to be a styling issue in Stripe not specific to Storefront.

Sounds like it would be best to fix it in Stripe plugin - good thinking @Aljullu, I agree 😃

**Comment by nielslange** [comment] 2020-10-24 03:32
Good catch, @Aljullu. I also think that addressing this issue in https://github.com/woocommerce/woocommerce-gateway-stripe/ makes the most sense.

**Comment by budzanowski** [comment] 2020-11-26 11:06
I have added this problem to a related opened issue in the Stripe repository https://github.com/woocommerce/woocommerce-gateway-stripe/issues/911

Closing.

**Closed by budzanowski** 2020-11-26 11:06 UTC
Labels: Priority: Low, Status: has-pr, Type: Bug
