### ISSUE TITLE
Hide content section when empty on the homepage template

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#673] opened 2017-10-26 16:07 UTC
1. Create page
2. Assign homepage template
3. Ensure it has an empty title / content
4. Publish
5. Notice a large empty section on the frontend

Something like 

```
.page-template-template-homepage .site-main > .type-page:empty { 
display: none; 
}
``` 

oughta do it.

**Comment by GlennMartin1** [comment] 2017-10-26 17:17
Sorry to ask here - but what's the projected time-frame for 2.3.0?

**Comment by jameskoster** [comment] 2017-10-27 10:03
@GlennMartin1 Hopefully by the end of the year but no certain date as yet.

**Comment by ry167** [comment] 2017-10-28 04:59
@jameskoster I'm not entirely sure what the issue is here?

When pages without the 'Homepage' template are viewed they are blank as well?

Here is a screenshot with the current state and another with the CSS you suggested:
![storefront-empty-page-nocss](https://user-images.githubusercontent.com/961043/32131394-924d461c-bc09-11e7-902e-68b921e3596e.png)
![storefront-empty-page-css](https://user-images.githubusercontent.com/961043/32131393-92207d9e-bc09-11e7-90fa-b6a00c6a57d1.png)

Should I submit a pull request for that change?

**Comment by jameskoster** [comment] 2017-10-30 11:37
@ry167 the issue is slightly different on the homepage template because of two things;

1. The homepage content `section` has quite large padding which creates the spacing when it's empty
2. There is content displayed beneath that `section`

So the result is that when the homepage content is left empty the rest of the stuff on that page is pushed down and you see an ugly, confusing blank space.

**Comment by tiagonoronha** [comment] 2018-02-06 15:02
I had a PR open (#756) to remove the Homepage section when there's no title and no content, but I don't really like that solution because then in WordPress the page gets the "no title" description.

I think a fair solution to this problem is to include instructions on how to remove the Content section using the hooks. Alternatively, we can think of something else like a toggle in the Customizer.

**Comment by tiagonoronha** [comment] 2019-02-27 19:38
Closing this issue since we'll soon start looking into replacing the homepage template with a regular page with Gutenberg blocks.

**Closed by tiagonoronha** 2019-02-27 19:38 UTC
Labels: Type: Enhancement
