### ISSUE TITLE
@JamesKoster WooCommerce 3.0 won't advance pages with long captions

### ISSUE THREAD

**Issue by GlazerGallery** [woocommerce/storefront#565] opened 2017-04-18 20:56 UTC
Here's a link to a page where I am having this problem. Click the magnifier icon, then when it takes you to the next screen, click the right arrow. It goes right back to the product page and does not advance to the next image and caption. The same thing happens in both Storefront and Vantage, and I do hope to be able to go back to Vantage, because I had it looking exactly the way I wanted before the WooCommerce 3.0 update, but I'll leave it in Storefront for now so you can troubleshoot it more easily. https://www.georgeglazer.com/wpmain/product/dr-robert-john-thornton-folio-botanical-prints-from-the-temple-of-flora/.

Note that I do not have a Storefront child theme because I don't really want one. I want to be able to use WooCommerce with Vantage, which had the look I wanted, and I already had done a lot of work to customize it and don't want to have to redo all that.

Note also that the site as a whole is still incomplete. We've got another 750+ products to proofread and I still have to make icons for some of the categories before we make it public. So if it looks unfinished (including the fact that the adjustments I'd made to the design in Vantage aren't visible in Storefront) that's because it isn't.

**Comment by jameskoster** [comment] 2017-04-19 09:43
Thanks for the link. This isn't a Storefront or a Vantage issue. The problem is caused by the length of your captions. They are so large that the magnified version of the image is actually smaller than the original.

Why not put these long captions in the product description, which is probably where they belong?

I'm closing this as it's not an issue in Storefront.

**Closed by jameskoster** 2017-04-19 09:43 UTC
