### ISSUE TITLE
previous / next article buttons not working correctly (within the same article category)

### ISSUE THREAD

**Issue by Thomas-1985** [woocommerce/storefront#1340] opened 2020-04-29 20:20 UTC
Description:
In version 2.5.5 the next / previous buttons don't work properly within the same product category (also tested with 2.5.3).

I set the following in my functions.php

        // Show only products in the same category?
        $in_same_term   = apply_filters( 'storefront_single_product_pagination_same_category', true );

Expected behaviour:
-When i navigate to the first article in the category, the previous article button should disappear
-When i navigate to the last article in the category, the next article button should disappear

Actual behaviour:
-For all articles (including first and last) both buttons are available. When i click the previous article button on the first article, the last article from another category is shown (the same is true for the last article in the category).

Browser environment (tested with):
Firefox 75.0
Safari

**Comment by haszari** [comment] 2020-04-29 21:52
Thanks for reporting this @Thomas-1985.

Can you confirm that this issue occurs with only Storefront and WooCommerce active? I can't reproduce the issue. In my test site I'm using the Woo sample product data. In the `Clothing` category for example, the first/last page buttons are correctly disabled as I'd expect. Here's a screen recording for what I'm seeing:

![category-pagination](https://user-images.githubusercontent.com/4167300/80650395-0b8b6b00-8ac8-11ea-88b0-e324ee2030a1.gif)
If you're still seeing an issue, can you share more details - simple steps to reproduce the problem, and screenshots showing the bug. Thank you :)

**Comment by nerrad** [comment] 2020-07-17 18:50
While possibly related to #1411 it looks like we could still use more details for this specific reported issue. I'm going to close this for now because there hasn't been a reply from the reporter for nearly 3 months. The issue can still be commented on and re-opened if necessary.

**Closed by nerrad** 2020-07-17 18:50 UTC
Labels: Status: Needs Author Feedback
