### ISSUE TITLE
Make responsive the homepage featured image

### ISSUE THREAD

**Issue by thomasschmit** [woocommerce/storefront#685] opened 2017-11-16 15:57 UTC
Currently, whatever screen size and pixel density, the homepage featured image is displayed without being resized. Therefore, if the picture weights 5 Mo, these 5 Mo are loaded, even on a phone. Isn't it possible to use media queries to adapt image size depending on the device? It'd make the page lighter and the load faster.

Thanks by advance :)

**Comment by jameskoster** [comment] 2017-11-17 11:20
The problem is that we're loading it as a background image. So we have to support the largest viewport first. It's not ideal I confess. 

We could add an image size to prevent _extremely_ large images as an enhancement.

But to make the image truly responsive we'd need to output it inline rather than setting it as a background. That way WordPress' responsive images feature would handle the sizing. Should be simple enough, we'd then just need to absolutely position it centrally, tweak the z-index and set `overflow: hidden` on the homepage content section.

Worth experimenting with for sure.

**Comment by porlz** [comment] 2018-06-14 09:07
Why are the developers so incompetent as not to be able to fix this simple problem that should never have existed in the first place? Its a simple fix like every other theme developer does it, variable header height and the ability to fix the image header width by pixels or percentage. 
Right now the theme does as it wants to do. Problem is the kids they call developers dont stress test anything at all.

**Comment by tiagonoronha** [comment] 2019-03-12 12:24
The homepage template is on its way out and will be replaced by Gutenberg blocks so this issue is no longer relevant.

Closing.

**Closed by tiagonoronha** 2019-03-12 12:24 UTC
Labels: Type: Enhancement
