### ISSUE TITLE
Button size: cart vs. checkout

### ISSUE THREAD

**Issue by uok** [woocommerce/storefront#1420] opened 2020-07-12 12:06 UTC
Hello,

Why does the button "proceed to checkout" on cart page have bigger padding/font-size/width compared to the "place order" button on the checkout page?

**Comment by nerrad** [comment] 2020-07-17 19:29
Hi there, 

Would you be able to share some screenshots illustrating what you are seeing?

**Comment by uok** [comment] 2020-07-18 08:05
Sorry, I found another plugin places the button at the end of the checkout form, which is outside the last div and therefore the default woo css is not applied.

**Comment by uok** [comment] 2020-07-18 08:06
Sorry, I found another plugin places the button at the end of the checkout form, which is outside the last div and therefore the default woo css is not applied.

**Comment by nerrad** [comment] 2020-07-18 09:48
I’m interpreting your reply meaning you found a solution, so I’ll close this issue. If I’ve interpreted incorrectly you can still leave a comment with more details about what the problem is and we can consider reopening.

**Closed by nerrad** 2020-07-18 09:48 UTC
Labels: Status: Needs Author Feedback
