### ISSUE TITLE
Prev/Next buttons on Product Page not working properly.

### ISSUE THREAD

**Issue by tommyshellberg** [woocommerce/storefront#1185] opened 2019-07-16 11:24 UTC
**Setup:**

WooCommerce latest(3.6.5) and Storefront 2.5.1.

**Expected:**

The Prev/Next buttons added by Storefront should show the *next* available product(in the same category) by ID as well as the *previous* product based on the ID. If we reach the end of the list it should circle back to the beginning.

**Issue:**

* The `get_adjacent()` method is not returning a post; it's returning null which causes the product to be retrieved using the `query_wc()` method:

https://github.com/woocommerce/storefront/blob/master/inc/woocommerce/class-storefront-woocommerce-adjacent-products.php#L103

To test, load up a new WC installation with Storefront and install the dummy content:

![](https://cdn-std.dprcdn.net/files/acc_403067/sJ4bBD)

The Beanie product shows Belt for both prev/next:

![](https://cdn-std.dprcdn.net/files/acc_403067/33yL9S)

And the Belt only shows Beanie:

![](https://cdn-std.dprcdn.net/files/acc_403067/YWNoTl)

**Comment by codestor4** [comment] 2019-08-14 21:33
I couldn't reproduce this on WC 3.7.0, Storefront 2.5.1 and WP 5.2.2 on localhost. Tested by installing fresh WP, WC, Storefront and dummy data.

**Comment by juliaamosova** [comment] 2019-11-15 15:21
@tommyshellberg I also can't reproduce this. I know it's been a while since the issue was opened. Apologies for getting to this so late. Can you please test again to see if you can still reproduce with WC 3.8 and Storefront 5.2.3?

**Comment by GlennMartin1** [comment] 2019-11-15 15:23
That's been discussed before here: https://github.com/woocommerce/storefront/issues/848#issuecomment-386105350

**Comment by juliaamosova** [comment] 2019-11-15 15:27
Thank you for referencing where the issue was previously discussed @GlennMartin1. I am closing this issue as per https://github.com/woocommerce/storefront/issues/848#issuecomment-386105350.

**Closed by juliaamosova** 2019-11-15 15:27 UTC
Labels: Status: Needs Author Feedback
