### ISSUE TITLE
Sticky Add-to-Cart - Add support for small screens

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#856] opened 2018-05-08 20:21 UTC
WordPress 4.9.5
Storefront 2.8

Works on a desktop, or in "desktop mode."

Does not display on Android (mobile Chrome).

**Comment by tiagonoronha** [comment] 2018-05-09 10:25
Hi! It's currently intended to only work on desktop devices.

Let's leave this issue open as an enhancement.

**Comment by By-oussef** [comment] 2018-12-31 21:33
+1

**Comment by ferrassi** [comment] 2019-03-12 14:51
+1

**Comment by ben72** [comment] 2019-03-12 15:11
+1

**Comment by shubhsheth** [comment] 2020-05-14 03:44
I created a pull request to close this issue. Can someone review it?

**Comment by haszari** [comment] 2020-05-14 03:51
Thanks @shubhsheth – I'll take a look.

Note - this is arguably a new feature, as the original feature was designed to be desktop-only. Work in Storefront is mostly focused on safe fixes and compatibility updates right now.

**Comment by haszari** [comment] 2020-05-14 04:00
Added to 2.5.7 for consideration / investigation. 

If this works well from a design/flow point of view, is safe (won't break / impact existing stores), then perhaps we can include in 2.5.7.

**Comment by haszari** [comment] 2020-05-15 02:12
Closing - as discussed in the PR, the sticky header is of limited use on small screens, and competes with the sticky footer for attention. We don't want to include this behaviour in Storefront for all stores.

Stores that would like this sticky header on mobile can implement in a child theme, custom plugin, or customizer css, using #1312 as a guide.

Thanks for prototyping this @shubhsheth !

**Closed by haszari** 2020-05-15 02:12 UTC
Labels: Type: Enhancement
