### ISSUE TITLE
Widget Visibility: Storefront or Products widget does not enforce widget visibility preferences in the sidebar

### ISSUE THREAD

**Issue by pauljacobson** [woocommerce/storefront#1612] opened 2021-02-18 06:19 UTC
## Describe the bug

Our customer has a Products widget in the _Sidebar_ widget area on their site. They don't want the widget to appear on the shop page, or on the checkout page.

We set widget visibility preferences for the widget to adjust where the widget should display, like this:

<img width="465" alt="Markup 2021-02-17 at 14 02 45" src="https://user-images.githubusercontent.com/2912202/108202236-78d8bd00-7129-11eb-8ad3-4b23301c9efe.png">

I noticed this issue when I tested with the Independent Publisher 2 theme (I picked the theme because it has sidebar support).

Issue follow-up with our customer: 3746768-zen

## To Reproduce

1. Go to _Customizer_ > _Widgets_ > _Sidebar_
2. Click on Products widget, and then select _Visibility_
3. Change widget visibility
4. See widget still displaying on a page it should be hidden on.

## Screenshots

See above

## Expected behavior

Widget visibility preferences should be applied, and a widget should not appear on pages it is set to be hidden on.

### Browser Environment

- Platform: macOS 11.2.1
- Browser(s): Firefox Developer Edition v86.0b9 

### WordPress Environment

WordPress WordPress.com Business plan site

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://todds-treats.com
Site address (URL): https://todds-treats.com
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: 5.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.15
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.75.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 3.21MB
Database Data Size: 1.79MB
Database Index Size: 1.42MB
wp_woocommerce_sessions: Data: 0.23MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 0.36MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.27MB + Index: 0.06MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 11
customize_changeset: 26
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 10
page: 8
post: 5
product: 6
revision: 47
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Akismet Anti-Spam: by Automattic – 4.1.8
AMP: by AMP project contributors – 2.0.10
CoBlocks: by GoDaddy – 2.8.1
Crowdsignal Forms: by Automattic – 1.3.5
Facebook for WooCommerce: by Facebook – 2.3.0
WordPress.com Editing Toolkit: by Automattic – 2.19
Gutenberg: by Gutenberg Editor Team – 9.9.3
Jetpack by WordPress.com: by Automattic – 9.4.1
Layout Grid: by Automattic – 1.5
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
Page Optimize: by Automattic – 0.5.1
Storefront Powerpack: by WooCommerce – 2.0.0
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 3.2.5
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.8.0
WooCommerce Product Add-ons: by WooCommerce – 3.3.1
WooCommerce Shipping & Tax: by Automattic – 1.25.7
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.40
WooCommerce: by Automattic – 5.0.0

### Inactive Plugins (12) ###

Classic Editor: by WordPress Contributors – 1.6
Klarna Checkout for WooCommerce: by Krokedil – 2.4.3
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.2.0

WooCommerce Australia Post Shipping: by WooCommerce – 2.4.28
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.19
WooCommerce eWAY Payment Gateway: by WooCommerce – 3.1.25
WooCommerce PayFast Gateway: by WooCommerce – 1.4.18
WooCommerce Payments: by Automattic – 1.9.2
WooCommerce Royal Mail: by WooCommerce – 2.5.33
WooCommerce Square: by WooCommerce – 2.3.4
WooCommerce UPS Shipping: by WooCommerce – 3.2.31
WooCommerce USPS Shipping: by WooCommerce – 4.4.49

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
Taxonomies: Product Visibility: 
Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #101 - /shop/
Basket: #103 - /basket/
Checkout: #105 - /check-out/
My account: #107 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 20
Oldest: 2021-02-13 12:16:23 +0000
Newest: 2021-02-17 12:44:09 +0000

`
```
</details>

**Comment by Aljullu** [comment] 2021-02-23 13:32
Hi @pauljacobson, thanks for opening this issue. I tested the Widget Visibility functionality of Jetpack with Storefront and it seems to work fine for me. Is there anything I'm missing? It's not clear to me from the issue description if your issue is with Storefront or with Independent Publisher 2. If it's the second, you should probably log the issue in their repo since this one is only about the Storefront theme. :slightly_smiling_face:

**Comment by pauljacobson** [comment] 2021-02-23 16:07
Hi @Aljullu Thanks for the feedback. I'm not entirely sure where the issue is here. It doesn't seem to be limited to Storefront because I could reproduce in Independent Publisher 2. It's not limited to that theme either, for obvious reasons.

I'm not sure where this issue should be, though? Given that this affects the Products Widget, perhaps the WooCommerce repo?

**Comment by Aljullu** [comment] 2021-02-24 08:59
Yeah... if it's reproducible in several themes, probably it's not a bug specific to Storefront. Given that the Widget Visibility feature is from Jetpack, I would open the issue in [Jetpack's repo](https://github.com/Automattic/jetpack/), I think they will be able to investigate a bit more what's going on and point you in the right direction.

I will close this issue for now since it doesn't seem to be a bug in Storefront.

**Closed as completed by Aljullu** 2021-02-24 08:59 UTC
