### ISSUE TITLE
Google error: Either "offers", "review", or "aggregateRating" should be specified

### ISSUE THREAD

**Issue by sandrodz** [woocommerce/storefront#1072] opened 2019-03-07 06:44 UTC
This error comes from (google srearch console) the fact that the schema.org markup in some product listing pages is lacking a required field.

Category template and shop home template need to be fixed.

<img width="490" alt="screen shot 2019-03-07 at 10 43 24 am" src="https://user-images.githubusercontent.com/8479569/53937198-dd79e900-40c5-11e9-8a5a-ebbcfeb7cf86.png">

**Comment by ben72** [comment] 2019-03-07 07:18
Duplicate of #1064

**Comment by sandrodz** [comment] 2019-03-07 07:20
@ben72 I've searched for it, but since issue poster used image instead of actually writing the error in text, there was no hit.

**Comment by ben72** [comment] 2019-03-07 07:22
@sandrodz Try a plugin like Yoast WooCommerce SEO plugin if you want to fix the issue.

**Comment by tiagonoronha** [comment] 2019-03-07 14:47
Other plugins that you can use:

https://wordpress.org/plugins/wordpress-seo/
https://wordpress.org/support/plugin/wp-structuring-markup
https://plugin.squirrly.co/wordpress/seo/

Thank you!

**Closed by tiagonoronha** 2019-03-07 14:47 UTC

**Comment by ben72** [comment] 2019-03-07 16:47
@sandrodz This recent fix in WooCommerce might help on this, https://woocommerce.wordpress.com/2019/03/07/woocommerce-3-5-6-fix-release/

**Comment by sandrodz** [comment] 2019-03-08 10:05
@ben72 yep, that fixes it.
