### ISSUE TITLE
My Account – tab “Orders”, Mobile version

### ISSUE THREAD

**Issue by kolarpav** [woocommerce/storefront#2150] opened 2024-05-19 18:16 UTC
Hi,
I would like some advice on the “My Account” widget from Elementor, please. In the mobile version, on the “Orders” tab, the text for the given order is not displayed on the line before the colon (only the colon is displayed). That is for example, this particular text is not displayed: Order number, Date, etc., only a colon is displayed and this text disappears. In the desktop and tablet version everything is fine, it is displayed as the heading of the given column. I also found it to be fine in Elementor. Maybe there is a bug directly in the WooCommerce plugin.
Does anyone have experience with this problem?
Thank you in advance for your reply and any advice.

**web:** https://www.bozp-consult.cz

<img width="344" alt="Snímek obrazovky 2024-05-14 074944" src="https://github.com/woocommerce/storefront/assets/170264185/c8c07834-38e4-42c6-850e-62f1efeb204c">
<img width="1055" alt="Snímek obrazovky 2024-05-14 075115" src="https://github.com/woocommerce/storefront/assets/170264185/70deea3c-c834-46a0-9807-856ff20d75ef">

**Comment by kmanijak** [comment] 2024-05-21 07:56
Hi @kolarpav,

> Maybe there is a bug directly in the WooCommerce plugin.

I tried to reproduce with standalone WooCommerce and the content is displayed correctly:
![Image](https://github.com/woocommerce/storefront/assets/20098064/65e40686-75b6-4763-9a8e-9f62d873268e)

Do you mind sharing more details about this issue:
- What versions of WordPress, WooCommerce and Elementor you use.
- Steps to reproduce.

Thanks!

**Comment by kolarpav** [comment] 2024-05-21 11:54
Wordpress version: 6.5.3
Elementor version: 3.19.4 (or I also tried 3.21.5)
WooCommerce version: 8.8.3

No one has helped me yet, everyone blames it on the other plugin developer.

That is thank you very much for your help and advice.

**Comment by kolarpav** [comment] 2024-05-21 12:04
Otherwise, I tried it with other plugins from other providers, e.g.
by Crocoblock. The result is always the same. Therefore, I think the error will be in WooCommerce.

Thanks for the reply and any advice.

**Comment by kmanijak** [comment] 2024-05-21 12:09
> Wordpress version: 6.5.3
> Elementor version: 3.19.4 (or I also tried 3.21.5)
> WooCommerce version: 8.8.3

Thanks for providing these!

Can you share the steps to reproduce? Do you do anything specific to see that result? Is it just having Elementor installed along with WooCommerce to reproduce it?

EDIT: I tried reproducing with Elementor 3.21.6 activated and couldn't reproduce the issue. Any chances you have some custom CSS/JS applied on a page that may hide the table headers?

**Comment by kolarpav** [comment] 2024-05-21 12:31
The "My Account" plugin used is directly from Elementor. I'm using custom CSS, but I don't know if it could hide any headings. Otherwise, what reproductive steps do you have in mind?

**Comment by kolarpav** [comment] 2024-05-21 12:43
I deleted my own css, and the same result.

**Comment by kmanijak** [comment] 2024-05-22 07:50
I'm sorry you're experiencing this problem.

> The "My Account" plugin used is directly from Elementor.

That sounds like it's out of the scope of WooCommerce or Storefront. But you also mentioned:

> I also found it to be fine in Elementor.

Have you tried deactivating Elementor and see if that works with WooCommerce only?

**Comment by kolarpav** [comment] 2024-05-22 11:47
Hi,
without Elementor the whole website is broken, I tried it. And that means I can't check the functionality of the "My Account" widget. Otherwise, I also tried disabling the YellowPencil plugin, but also to no avail.
Someone told me on the Czech Facebook group "WordPress..." that it was caused by a bad web address; i.e. where is the e-shop located? But I don't know what exactly he meant.
I still think there is a bug in the WooCommerce plugin.
![V Elememtoru](https://github.com/woocommerce/storefront/assets/170264185/19750098-dea6-4843-a8b3-4d81c90d59a8)

**Comment by kolarpav** [comment] 2024-05-22 11:57
As you can see from the picture - see above, right in Elemtor everything is correct.

**Comment by kmanijak** [comment] 2024-05-22 13:32
> The "My Account" plugin used is directly from Elementor.
> ...
> And that means I can't check the functionality of the "My Account" widget.

As "My Account" widget is Elementor Pro feature I suggest contacting the support of Elementor Pro. As the Element Pro is a paid product, we cannot access the code or try reproducing the issue fully without having to purchase a license. I suggest reaching out to their support again and hopefully getting another support agent who can assist you.

In the meantime, I'll go ahead and close this issue but please be advised closed issues can still be commented on. 🙌

**Closed as completed by kmanijak** 2024-05-22 13:32 UTC
Labels: needs feedback

**Comment by kolarpav** [comment] 2024-05-23 11:39
The problem is that I also tried it with the "JetWoobuilder to CrocoBlock" plugin and their "Orders" widget and the problem is still the same. From this I concluded that the error must be in WooCommerce and not in Elementor. 
Does that mean you can't advise me?

**Comment by kmanijak** [comment] 2024-05-24 06:30
>I also tried it with the "JetWoobuilder to CrocoBlock" plugin and their "Orders" widget and the problem is still the same.

"JetWoobuilder to CrocoBlock" is also a paid plugin that we don't have access to. But as far as I can see it's still based on Elementor, meaning that the same conflict may occur with and without an additional "JetWoobuilder to CrocoBlock" plugin. I'd still suggest contacting the support of Elementor.

> Does that mean you can't advise me?

One thing we can try is this: do you mind sharing the Elements structure screenshot like in the screenshot below? On the `td` elements there should be a `data-title` attribute based on which the table's `:before` content is set.

![Screen Shot 2024-05-24 at 08 22 57 AM](https://github.com/woocommerce/storefront/assets/20098064/3b2c35fb-cb25-4c81-b8fe-7565b21cd1c9)

**Comment by kolarpav** [comment] 2024-05-24 09:33
Thanks for the help and advice. I already solved it. The problem was with the "Img Title Removal" plugin, which was supposed to remove titles only from images.

**Comment by kmanijak** [comment] 2024-05-24 10:12
Great you solved that! 🙌
