### ISSUE TITLE
StoreFront WooCommerce Single Product Gallery thumbnails loading page resize bug

### ISSUE THREAD

**Issue by justdudeone** [woocommerce/storefront#1249] opened 2020-01-20 08:12 UTC
Hello,
Default WooCommerce theme StoreFront have a one old and very annoying bug which cause each WooC Single Product Gallery to jumping-twitching on page loading because of mistake at product gallery thumbnails loading. StoreFront theme load product gallery thumbnails with a too huge size and with vertical alignment - so only after thumbnails images loading completed and image takes a lot of vertical space, browsers resize and position them horizontally. This cause page to intensely stretching-expanding vertically on thumbnails loading and after load completed - page are shrinks-compress to a correct size. This jumping-twitching affect are easily visible on loading pages with many product photos 5-10 and a specially at slow internet connections or old PC/smartphones - it's looks very-very bad-crookedly!
Other themes does not have this problem.
It's a base bug at your theme and your developers must resolve it!

**Comment by nielslange** [comment] 2020-03-01 13:21
@justdudeone Could you create a small GIF that demonstrates this issue? When looking up the gallery images on a fresh WordPress, WooCommerce and Storefront installation, I cannot reproduce this issue? Or do you have a testing sit on which this issue can be looked up?

**Comment by justdudeone** [comment] 2020-03-01 14:28
![WooC_Product_Gallery_on-loading](https://user-images.githubusercontent.com/43311177/75627518-eff80700-5be1-11ea-96d2-5063915eceb7.png)

**Comment by justdudeone** [comment] 2020-03-01 14:41
One more problem - gallery does not change main photos resolution automatically when gallery rise in size - for example browser window stretching, move browser to bigger screen, to projector, etc - main image stay small and because of low resolution - blurred.
To resolve this problem - user must reload page one time - after that resolution of main images updates. But it must also work on loading or on screen size changes etc.
![WooC_Product_Gallery_resolution](https://user-images.githubusercontent.com/43311177/75627712-b32d0f80-5be3-11ea-98d1-b4777f1aa639.png)

**Comment by nielslange** [comment] 2020-03-01 15:34
On my end, the images load exactly as seen on https://themes.woocommerce.com/storefront/product/build-your-dslr/#camera-body:

<img width="838" alt="Screenshot 2020-03-01 at 22 32 32" src="https://user-images.githubusercontent.com/3323310/75628528-922ce480-5c0c-11ea-9899-47127dc367d3.png">

Are you using the latest versions of WordPress, WooCommerce and Storefront and do you see the same issue when only using WordPress, WooCommerce and Storefront with no other plugins activated?

**Comment by justdudeone** [comment] 2020-03-01 16:24
You still don't understand. FINALLY - YES - images and thumbs loads and align horizontally. But ON LOADING (if internet connection are too slow, or PC-smartphone CPU are slow, or product have too much images, etc) - user have time to see a place of content after WooC Product Gallery which have a huge margin for example 800px, but after all gallery thumbs and images loads - margin becomes smaller for example 400px and all content after gallery jumps up!
(To see this problem you can use at YOUR browser - Network conditions - Throttling or slow connection.)

**Comment by nielslange** [comment] 2020-03-01 16:58
Please note that I’m simply trying to understand this issue. No need to get upset and/or use caps. A detailed description of this issue could have avoided my questions. Please also note that Storefront is an open source theme and not a premium theme. If you expect this issue to get fixed it would be nice to act supportive rather than demanding and passive aggressive. Comments such as _"It's a base bug at your theme and your developers must resolve it!"_ might not work in your best interest.

**Comment by justdudeone** [comment] 2020-03-02 08:01
How StoreFront can be a "free open source sw which made by a volunteers" if it have a payable Pro (extensions bundle) version - so both free and pro versions must have the same bugs and the same developers...?
https://woocommerce.com/products/storefront-extensions-bundle/

**Comment by nielslange** [comment] 2020-03-02 09:01
If Storefront wouldn't be open source, you wouldn't find it in a public GitHub repo. This also counts for the free child themes, e.g. https://github.com/woocommerce/deli.  In comparison, you won't find any of the paid extensions in a public GitHub repo. It's up to the individual developers to build paid child themes and paid extensions on top of an open source product. That's the beauty of open source in general, and in case of WordPress, the GPL in specific. You could also create premium child-themes for Storefont and sell them. No one will stop you doing so. 

Instead of demanding that something, of which you think is a bug, gets fixed, I want to invite you to try finding a solution and submit a pull request. 😀

**Comment by justdudeone** [comment] 2020-03-02 10:32
I'am NOT a web-dev but still solutions are very obvious for me. Just try new 2020 theme - it does not have such problems. So you can compare differences and found how to fix StoreFront theme.

**Comment by GlennMartin1** [comment] 2020-03-02 13:47
@justdudeone 

- What version of WordPress are you running?
- What version of WooCommerce are you running?
- What version of Storefront are you running?
- What child-theme are you using? What version of that child-theme?

Can you share a URL to a page with the issue?

**Comment by justdudeone** [comment] 2020-03-02 14:34
All last versions and problem still does not resolved, original theme.
Just next content placed straight under WooC Product Gallery - so on page loading this content a hugely moved down, after gallery images loaded and arranged horizontally - content jumps up to a right position.

This problem cause because on page building StoreFront theme reserve too much vertical free space for a gallery thumbs, what does not need, because after loading images will arranged horizontally.

I tired to again and again explain so obvious problem which even not one of you can't test properly, omg.

**Comment by nielslange** [comment] 2020-03-02 15:28
> I tired to again and again explain so obvious problem which not one of you even can't test properly, omg.

As mentioned in https://github.com/woocommerce/storefront/issues/1249#issuecomment-593110328 already, I am unable to reproduce this issue on my end. Even when throttling down the loading time to 56 kb/s, I'm unable to reproduce this issue on my end as seen in https://d.pr/i/z8pbj0/XDzYFPYvxI

Both @GlennMartin1 and I are not trying to fight you here, but to get the necessary information to address this issue. While I cannot speak for @GlennMartin1, I can say that I'm not getting paid to contribute to the Storefront theme, but donate my free time to improve this theme. And as much as I hate repeating myself, with comments such as _"It's a base bug at your theme and your developers must resolve it!"_ and _"I tired to again and again explain so obvious problem which not one of you even can't test properly, omg."_ you're not making any friends in the open source community. Enough said ... I'm officially out of this issue. ¯\_(ツ)_/¯

**Comment by justdudeone** [comment] 2020-03-02 15:52
I just shocked of all your (un) professional level.
How you want to see that gallery on loading takes too much free space... when you look to a EMPTY WHITE SPACE?!?! OMG!!!
At least add a simple graphic line after-behind the product gallery!!! Thus you can see how this line or any other content will jumping above gallery!!!
TT

**Comment by justdudeone** [comment] 2020-03-02 16:20
![TRY_TO_ADD_LINE](https://user-images.githubusercontent.com/43311177/75695314-ed1d1500-5cba-11ea-9442-e0ef83ce464e.png)

**Comment by GlennMartin1** [comment] 2020-03-02 16:28
According to https://www.wpthemedetector.com/ the website that @justdudeone is inquiring about (https://www.capanet.org/product/patient-ninja/) is using a theme/child-them called **Intensity**.

**Comment by justdudeone** [comment] 2020-03-02 16:33
Wuahhahahahaaha!!!!
It's a screenshot from video of a "nielslange"!!!
OMG!

**Comment by GlennMartin1** [comment] 2020-03-02 16:38
Ok, evidently I was wrong.

I've resorted to guesswork (and evidently a wrong conclusion) since the questions I asked above (including https://github.com/woocommerce/storefront/issues/1249#issuecomment-593409977) have received no resposne.

There's no incentive for me to continue here. I wish you the best.

**Comment by justdudeone** [comment] 2020-03-02 16:40
OMG. You all are fkng IDIOTS!

**Comment by nerrad** [comment] 2020-07-13 16:15
Hi there, 

I realize this is a little bit after the fact but I do want to share that you had two people willing to help try to resolve this issue but your behaviour drove them away. It's a great opportunity to be introspective and reflect on how you communicated in this thread to produce a result that doesn't seem very beneficial to you.

I can understand how it'd be frustrating to not have things work as you expect, but I can assure you there are folks motivated to help resolve bugs _when we can figure out how to reproduce that bug so we can find a solution_. Rooting out the cause of bugs isn't always straightforward and in this case could depend on anything from the versions of software in use, potential conflicts with other plugins, or even the type and size of images being used. 

You did not answer specific questions about your environment so that those wanting to help could try to reproduce locally and isolate what may be the cause of the behaviour you pointed out. 

I realize that you think "LAST released versions, default Storefront" might help, but it does not, that's why the questions were specific. Sometimes folks think they are being clear by using the terms like "last" or "latest" but that isn't always the case. Giving the precise version numbers allows for extra verification and for the person trying to reproduce to make sure they are synced up with the same versions.

Since there hasn't been a reply for a couple months, I'm going to close this issue. If you are still experiencing the bug, we welcome any additional details you can provide and will consider re-opening for further investigation. At a minimum, the questions [posted by Glenn here](https://github.com/woocommerce/storefront/issues/1249#issuecomment-593409977) _will need answered before we consider reopening_ and understand that if we _still_ can't reproduce there may be other questions for clarification.

Thanks.

**Closed by nerrad** 2020-07-13 16:15 UTC
Labels: Status: Needs Author Feedback
