### ISSUE TITLE
Reduce padding for Mix and Match mobile styles

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/storefront#2078] opened 2022-12-06 18:59 UTC
## Is your feature request related to a problem? Please describe.
Storefront has some built-in styling for Mix and Match products. When in mobile view though, there's rather a lot of padding around the table cells. 

## Describe the solution you'd like
Reduce padding for mobile.

## Additional context
![image](https://user-images.githubusercontent.com/507025/205997947-fc0b4b1b-1247-46c0-aa7e-c2c09f42e968.png)

**Comment by imanish003** [comment] 2022-12-22 06:59
Hi @helgatheviking, Thanks so much for reporting this issue! 🙏 

I tried reproducing the issue, but it isn't reproducing. I don't see any additional style added to `product-thumbnail` cell by Storefront for mix-and-match products, as you can see in screenshot below:
![image](https://user-images.githubusercontent.com/16707866/209074449-09a98371-027d-40cf-8a32-4ffb62529ddb.png)

There is a generic CSS style for table cell added by the storefront, which is overridden by mix and match product plugin CSS:
![image](https://user-images.githubusercontent.com/16707866/209075065-e2bb83a0-caf9-46fd-86e8-81e68ef29554.png)

Generic CSS will be added to all table cells & You may always override generic table CSS with custom CSS wherever required.

**Comment by helgatheviking** [comment] 2022-12-28 01:13
Is the call coming from inside the house? :) I'm in a bit of an end-of-year no-code mode, but I will try to check on this next week.

**Comment by imanish003** [comment] 2022-12-28 05:42
Hey @helgatheviking ,
Yes. No worries, take your time 🤝

**Comment by kmanijak** [comment] 2023-01-13 13:53
Hi @helgatheviking, I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as not planned by kmanijak** 2023-01-13 13:53 UTC

**Comment by helgatheviking** [comment] 2023-01-13 16:12
Finally looking again thanks to the GH notification... and it's definitely the padding in storefront:

![image](https://user-images.githubusercontent.com/507025/212366126-677096af-a816-42b7-8f4f-e41007fcfe51.png)

[Specifically this one](https://github.com/woocommerce/storefront/blob/trunk/assets/css/woocommerce/extensions/mix-and-match.scss#L14-L19):
```
.mnm_table .product-thumbnail, .mnm_table .product-name, .mnm_table .product-quantity, .mnm_table .container-quantity {
  padding: .6180469716em .875em !important;
}
```

at the smallest widths I think this padding is way too big and might be better wrapped in a media query.

I'm gonna take a look at mobile table styles on my end first and then see what might be needed here.
