### ISSUE TITLE
Conflicting CSS when previewing with WooCommerce Email Customizer

### ISSUE THREAD

**Issue by mattyza** [woocommerce/storefront#585] opened 2017-05-23 16:38 UTC
When previewing in the WooCommerce Email Customizer, the `table tbody td` selector's `background-color` is conflicting with the styling of WooCommerce core's emails, causing the header background to show incorrectly.

The default preview:
![image](https://cloud.githubusercontent.com/assets/880803/26365047/bc107b26-3fe6-11e7-82e5-6eeb199eeac0.png)

Disabling the selector, using the Chrome Inspector:
![image](https://cloud.githubusercontent.com/assets/880803/26365097/dbc1ca7e-3fe6-11e7-985c-d782f861ea5d.png)

I noticed similar behaviours with the rounded corners field, although that might be in WooCommerce core, as it rounds the main container's corners, yet not the header and footer containers themselves, creating an odd display.

cc @jameskoster @tiagonoronha

**Comment by jameskoster** [comment] 2017-05-23 19:09
Hmm, I'm not sure this is Storefront's responsibility. Isn't the issue that the themes styles are being loaded 'beneath' the emails? 

This will occur in any theme that styles tables via options in the Customizer. Based on that it makes more sense to fix in the extension imo.

**Comment by mattyza** [comment] 2017-05-24 10:27
Hmmm... I did some further digging, @jameskoster. WooCommerce Email Customizer doesn't inject any CSS into the email template preview, so it may be that WooCommerce is conflicting with this.

To what I see, there is a table being used in the email template (as a structural table). Storefront's CSS is being injected (because the Customizer is frontend), and this is being loaded after WooCommerce's email CSS.

Perhaps the priority order of the postMessage calls in the extension can be made later, to resolve this, without Storefront needing an update.

I'll look into that and see what I can find.

**Comment by jameskoster** [comment] 2017-05-24 11:08
Yeah it all makes sense. In Storefront we use settings specified in the Customizer to add colors to tables. Those styles being loaded (they're added inline) in the email preview and causing this issue. This will happen in any theme that uses Customizer settings to style any elements that appear in the email preview.

Ideally the email preview would only load it's own styles and remove those added by themes. I'm not sure on the feasibility of that though. The simplest solution I can think would be to wrap the email preview in a unique class and prefix all styles with that class. That way they'd have priority over anything the theme throws at them.

**Comment by tiagonoronha** [comment] 2017-05-30 10:02
I'm closing the issue since the issue is in the extension, not Storefront.

I suggest that you remove all enqueues of scripts and styles when doing the email preview. That way it should be compatible with all themes and plugins.

**Closed by tiagonoronha** 2017-05-30 10:02 UTC
Labels: [Priority] Low, [Type] Bug
