### ISSUE TITLE
Column Layout in Safari pushes last item onto next row

### ISSUE THREAD

**Issue by bonbonio** [woocommerce/storefront#1215] opened 2019-10-02 15:01 UTC
Hi,

Using StoreFront with no customisation, but in Safari on a mac whatever number of items I have, results in the last item going onto the next line.

e.g.

instead of 

xxxx

it renders

xxx
x

or

instead of
xxx

it renders

xx
x

Looks like the issue might be to do with % rounding in safari or something, but it only occurs on the homepage product listing, not the listing on the shop page.

Any chance of someone sharing the customised CSS to fix it (or releasing an update!). I have seen threads on SO which confirm this bug is what others see. Seems bug is also mentioned here: https://github.com/woocommerce/woocommerce/issues/18927 from ages ago.

**Comment by Aljullu** [comment] 2019-10-17 07:01
Thanks for opening this issue @bonbonio! This seems to be a duplicate of #1197 and should be fixed in #1217. I will proceed closing this issue so debate can concentrate there.

**Closed by Aljullu** 2019-10-17 07:01 UTC
