### ISSUE TITLE
Product pagination doesn't work properly with imported products

### ISSUE THREAD

**Issue by guicmazeredo** [woocommerce/storefront#1375] opened 2020-06-09 21:00 UTC
## Describe the bug
If the products on the store have been imported - instead of created manually through the dashboard - if you click on a product from a category page and then use the `previous/next` buttons on the left/right hand-sides, the pagination will transition between two or three products within that category without a logical order.   

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Import products to a test site. You can use the [Woo Sample Data](https://docs.woocommerce.com/document/importing-woocommerce-sample-data/)
2. Visit a category page on the live site.
3. Click on a product.
4. On the product page, navigate between products using the `previous/next` products pagination. You will notice that it's not possible to navigate between all products within that category. Instead, it's only possible to navigate between two or three products without a logical order. 

Check this screencast using the `Accessories` category as an example: https://d.pr/v/2WUNxe 

## Expected behavior

The pagination should transition between all products within that category. For instance, I created 5 products manually through the dashboard and assigned the `Music` category to them. Then, I followed the steps listed above and I could navigate between all the 5 products. Screencast: https://d.pr/v/8Jc7gE

### Browser Environment

- Platform: e.g. macOS Catalina Version 10.15.4 
- Browser(s): Chrome Version 83.0.4103.61

### WordPress Environment

WP 5.4.1
WC 4.2.0
Storefront 2.5.7
--

<details>
```
### WordPress Environment ###

WordPress address (URL): https://extra-silkworm.jurassic.ninja
Site address (URL): https://extra-silkworm.jurassic.ninja
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.6
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.30-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_
Total Database Size: 3.92MB
Database Data Size: 2.45MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
customize_changeset: 5
nav_menu_item: 3
page: 6
post: 2
product: 29
product_variation: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Companion Plugin: by Osk – 1.14
Jetpack by WordPress.com: by Automattic – 8.6.1
WooCommerce Services: by Automattic – 1.23.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce: by Automattic – 4.2.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.5
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2020-06-09 18:09:34 +0000
Newest: 2020-06-09 18:12:15 +0000
```
</details>

**Comment by GlennMartin1** [comment] 2020-06-09 21:06
This issue https://github.com/woocommerce/storefront/issues/848 explains the cause and remedy.

**Comment by guicmazeredo** [comment] 2020-06-09 21:10
Wow, that was fast. Should I close this issue then?

**Comment by guicmazeredo** [comment] 2020-06-10 00:41
To clarify, I believe it would be good this behavior could be avoided somehow. I'm just not sure if this issue should be here or on the WooCommerce repo. If it's the latter I can open a new issue there and close this one.

**Comment by GlennMartin1** [comment] 2020-06-10 01:39
I understand the root issue is in WordPress itself.

If the issue only exists with dummy data, then it's a pretty benign issue.

What's the use case where this becomes an issue in a production environment?

**Comment by nerrad** [comment] 2020-07-17 19:25
I'm going to close this issue because it's not really related to Storefront as has been noted already. I agree things could maybe work better, but my early analysis would suggest that the import process needs to be modified so that the timestamp on imported products has a slight variation for each product during import (or use the dates provided in the import). 

For now, the workaround is to modify the dates of the products after the import (which I realize can be a manual chore).

It would be good to create an issue in the WooCommerce core repository (assuming products are being imported by the native importer included with WooCommerce core). Also, worthwhile ensuring this is still an issue with WooCommerce core 4.3.

I'm going to close the issue here because there's nothing actionable in this repository. A theme shouldn't be controlling imports/dates on products.

**Closed by nerrad** 2020-07-17 19:25 UTC
Labels: Priority: High, Type: Bug
