### ISSUE TITLE
Homepage category images aren't centered on mobile

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/storefront#1298] opened 2020-03-20 19:42 UTC
## Describe the bug
Homepage images aren't centered on mobile/smaller screens.

![Screenshot](https://d.pr/i/gXpzjK+)
Screenshot link: https://d.pr/i/gXpzjK

Isolating the problem to version 2.5.5 as version 2.5.4 works as expected:

![Screenshot](https://d.pr/i/FDKXic+)
Screenshot link: https://d.pr/i/FDKXic

This commit appears to be to blame:

https://github.com/woocommerce/storefront/commit/b4d01df9163cc2c463a348f225ea93fa3706e3ce

Can likely resolve by making replacing `margin-bottom: ms(3)` with `margin: 0 auto ms(3)` here: https://github.com/woocommerce/storefront/blob/b4d01df9163cc2c463a348f225ea93fa3706e3ce/assets/css/woocommerce/woocommerce.scss#L357-L359

Can you have a look at this @senadir ?

**Comment by nielslange** [comment] 2020-03-21 04:28
Thanks for reporting this issue, @johndcoy. This issue is similar to https://github.com/woocommerce/storefront/issues/1296 and should be fixed by https://github.com/woocommerce/storefront/pull/1297.

@senadir & @haszari

**Comment by patelmagnets** [comment] 2020-03-29 13:56
Product images is not center 
please check https://d.pr/i/4wyDKh 
image and fixed bug
![Screen Shot 2020-03-29 at 16 11 29](https://user-images.githubusercontent.com/62841312/77850905-38134500-71f3-11ea-9614-4fe2191746b1.png)

**Comment by haszari** [comment] 2020-04-16 03:38
Tested to clarify the scope of what's affected. 

- This is affecting category images on the homepage (using homepage template).
- Affects screen / browser size between 370px and 760px (ish).

**Comment by haszari** [comment] 2020-04-16 03:42
I think this issue is a duplicate of #1283.

**Comment by haszari** [comment] 2020-04-16 23:06
Fixed by #1313

**Closed by haszari** 2020-04-16 23:06 UTC
Labels: Priority: High, Status: has-pr, Type: Bug
