### ISSUE TITLE
Mini Cart Price Update Issue?

### ISSUE THREAD

**Issue by lafaCodes** [woocommerce/storefront#1946] opened 2022-04-05 11:13 UTC
Hello all,

I'm new with woocommerce and PHP and I'm having small issue.

Any one having issue with updating the price-amount  on mini cart (e.g: 2 × $25.00)?

`<span class="quantity">2 × 
      <span class="woocommerce-Price-amount amount">
           <bdi> <span class="woocommerce-Price-currencySymbol">$</span>25.00</bdi>
      </span>
</span>`

When I add product from  **SHOP** page, I can see sale price on mini cart (e.g: 2 × $12.00) but when I add any product from **Single Product Page** the price-amount changes back to regular price to $25 (e.g 2x $25.00)?

Am I the only having this issue or I'm using wrong hook?

But I can see sale price when I add product from **SHOP** page, bit confused!

Also, my related product price is not giving me sale price.

Any help would be appreciated. 

Thanks in advance.

**Comment by frontdevde** [comment] 2022-04-08 14:42
Hi @r00sn, I'm not sure I fully understand the issue. I've added a product on sale both from the Shop and Single Product pages and it worked as expected. Could you maybe provide us with clear steps on how to reliably reproduce the issue you're experiencing? If possible screenshots could also help illustrate the issue. Thank you!

**Comment by tomasztunik** [comment] 2022-05-11 09:14
@lafaCodes if this is still an issue please try to provide more details about your store setup, used plugins etc. we were not able to reproduce the issue you mentioned based on the details provided. 

For the time being, we are going to close this issue but feel welcome to comment here and if this issue persist and we can reproduce it we'll re-open it.

**Closed as completed by tomasztunik** 2022-05-11 09:14 UTC
