### ISSUE TITLE
Duplicate categories on Shop page

### ISSUE THREAD

**Issue by thabotswana** [woocommerce/storefront#1531] opened 2020-11-10 10:03 UTC
## Describe the bug
When you set the Shop page to display categories, it displays the categories twice.

When I previewed in the _Twenty Twenty_ theme, the categories are not duplicated.

- [x ] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Go to _Customize ▸ WooCommerce ▸ Product Catalog_
2. Select "Show categories" under **Shop page display**
3. See error

## Screenshots

<img width="1191" alt="Screenshot 2020-11-10 at 11 30 44" src="https://user-images.githubusercontent.com/35628116/98657368-7573af80-234a-11eb-92cc-9e5c45742147.png">

## Expected behavior
Categories should not be displayed twice. They should only appear once like in the screenshot below.

<img width="1191" alt="Screenshot 2020-11-10 at 11 31 48" src="https://user-images.githubusercontent.com/35628116/98657686-cb485780-234a-11eb-9e1f-086dfb63bab8.png">

### Browser Environment
Please provide as much detail as possible about your testing environment.

- Platform: macOS Catalina Version 10.15.7
- Browser: Google Chrome

### WordPress Environment
WordPress 5.5.3
WooCommerce 4.6.2
Storefront 2.8.0
-- | --

Reported here: 3476952-zen

**Comment by Aljullu** [comment] 2020-11-10 10:21
Hi @thabotswana, thanks for opening this issue. Unfortunately, I'm unable to reproduce.

![imatge](https://user-images.githubusercontent.com/3616980/98660488-a7cede00-2345-11eb-9ff3-a49b64e5b448.png)

We just released Storefront 2.9.0, could you test if the issue is still reproducible in that version?

https://github.com/woocommerce/storefront/releases/download/version%2F2.9.0/storefront.zip

Also, could you verify that if you go to Products > Categories, there are no duplicate categories there?

Thank you in advance!

**Comment by wpniall** [comment] 2020-11-10 12:54
Hi @Aljullu,

I'm on the ticket now.

> Also, could you verify that if you go to Products > Categories, there are no duplicate categories there?

No, I don't see any duplicate categories.

When I scroll down from the first set of products on https://casamarengostudio.com/shop/ to the second set of products, the URL changes to https://casamarengostudio.com/shop/page/2.

Seems like the site loads the same categories for page 2 as page 1.

**Comment by Aljullu** [comment] 2020-11-10 13:50
> When I scroll down from the first set of products on https://casamarengostudio.com/shop/ to the second set of products, the URL changes to https://casamarengostudio.com/shop/page/2.

Hi @wpniall, I think there are two things happening here:

* The site is probably using another plugin that is loading page 1 and page 2 one after the other without pagination. I would say an 'infinite scrolling' plugin or something similar.
* At the same time, for some reason WooComerce shows the same contents in page 2 than page 1 (however, page 3 returns a 'not found' error, as expected). I could reproduce it in my install too, but this issue seemed to be unrelated to Storefront since I could reproduce it with Twenty Twenty as well. So it might be better to open an issue in [WooCommerce repo](https://github.com/woocommerce/woocommerce) about this?

**Comment by wpniall** [comment] 2020-11-11 06:50
Hi @Aljullu 

I thought it might be a plugin conflict. However, all the plugins except for one are developed by Automattic or WooCoomerce. I disabled the other plugin (https://wordpress.org/plugins/gallery-custom-links/) but the problem is still there.

I think the "infinite scrolling" feature might be connected to the Jetpack Infinite Scroll feature: https://jetpack.com/support/infinite-scroll/#theme. Disabling that feature removes the duplicate content. However, the content is still available on a separate page at https://casamarengostudio.com/shop/page/2/.

The only WooCommerce status warnings are:

- WooCommerce Stripe Gateway |   | by WooCommerce – 4.5.3 – Installed version not tested with active version of WooCommerce 4.6.2
- WooCommerce Shipping & Tax |   | by Automattic – 1.25.2 – Installed version not tested with active version of WooCommerce 4.6.2

I will post on the WooCoomerce repo then.

Thank you for your help!

**Comment by Aljullu** [comment] 2020-11-11 08:18
Thanks for the investigation @wpniall.

> I will post on the WooCoomerce repo then.

Great! Definitely this seems to be an issue either with WooCommerce core or Jetpack Infinite Scroll.

For now, I will close this issue here. If at some point there is some evidence that this is an issue with Storefront, feel free to reopen.

**Closed as completed by Aljullu** 2020-11-11 08:18 UTC
