### ISSUE TITLE
Image cropping Incorrect on Archive Pages

### ISSUE THREAD

**Issue by keninbassart** [woocommerce/storefront#1282] opened 2020-03-02 15:37 UTC
## Describe the bug

When setting an image as un-cropped, the archive pages are showing the image as partially cropped. This cropping also shows in the admin area: 

Archive  page
![archivepage](https://d.pr/i/6eV5Vl+)
Image Link: https://d.pr/i/6eV5Vl

Product Page: 

![productpage](https://d.pr/i/nqiDs6+)
Image Link: https://d.pr/i/nqiDs6

Admin Area: 

![Admin Area](https://d.pr/i/dWmWfB+) 
Image Link: https://d.pr/i/dWmWfB

Customizer: 

![customizersettings](https://d.pr/i/HtvsuA+)
Image Link:  https://d.pr/i/HtvsuA

## To Reproduce
 Upload an image with vertical aspect ratio 9 one in example is 699 x 1000 
Visit SF archive page

## Expected behavior
Images should load uncropped

**Comment by haszari** [comment] 2020-04-15 04:01
Thanks for reporting this @keninbassart - I'm keen to get a better idea of whether this is a new issue and what components are affected.

- Is this issue introduced recently, or has the `Uncropped` option broken in a recent Storefront release?
- Does this affect blocks as well as the traditional archive page?
- Does this affect the homepage template?

**Comment by keninbassart** [comment] 2020-04-27 13:29
>Is this issue introduced recently, or has the Uncropped option broken in a recent Storefront release?

It only appeared as of this version of Storefront. 

>Does this affect blocks as well as the traditional archive page?

It only shows as an issue on the archive pages and the admin area

>Does this affect the homepage template?

No, only the archive pages.

**Comment by haszari** [comment] 2020-04-28 03:22
Thanks for clarifying @keninbassart - I'm assuming you're seeing the issue in Storefront 2.5.5 (the current release version right now).

I tried to reproduce the issue and it seems to be working correctly for me. I tested on 2.5.6 RC 1, 2.5.4 and 2.5.5 and couldn't get the image to show cropped.

Here's the steps I tried. I tested in Firefox, Chrome and Safari on macOS.

- Enter `Customizer`
- Select `Uncropped` option in `WooCommerce > Product Images`
- Upload a tall image as product image for a product, click `Update` to save the product
- View the category page for that product, e.g. `Accessories`

<img width="1267" alt="Screen Shot 2020-04-28 at 3 19 20 PM" src="https://user-images.githubusercontent.com/4167300/80443587-a4ed3c80-8963-11ea-90c4-15db9ab11f1a.png">

**Comment by haszari** [comment] 2020-04-28 03:30
Aha! @keninbassart I think the perhaps the crop customizer option applies when the product image thumbnail is generated (when the image is set on the product). 

Can you try the following:

- Select `Uncropped` option in Customizer and publish.
- Upload a tall image to a product and update.
- View the category for that product.

If you upload the image after setting uncropped option, do you still see a cropped image?

**Comment by keninbassart** [comment] 2020-04-30 20:20
No change.

**Comment by haszari** [comment] 2020-04-30 20:24
Thanks for rechecking @keninbassart :) In that case, I'm stuck, as I can't reliably reproduce the issue myself. If you have steps that can reliably reproduce the issue, please add as much detail as possible so I can reproduce. Thank you!

**Comment by haszari** [comment] 2020-05-13 03:09
Switched this to low priority until we have a clearer idea of impact.

**Comment by nerrad** [comment] 2020-07-17 18:38
There hasn't been a reply to this issue for over two months. I'm going to close this for now but if there's any additional information that can be added to help us reproduce this please do leave a comment and we can consider reopening.

**Closed by nerrad** 2020-07-17 18:38 UTC
Labels: Priority: Low, Status: Needs Author Feedback, Type: Bug
