### ISSUE TITLE
Swipes gestures not working on iphone 6

### ISSUE THREAD

**Issue by keusta** [woocommerce/storefront#1226] opened 2019-11-04 11:37 UTC
This link come from thomas, an auttomatic engineer so its sure to be default instal (wp + woo + storefront) :
https://thomas.mystagingwebsite.com/product/logo-collection/.

When trying to swipe (left, right, down) on clicked product image it’s not working on Iphone 6.
https://cld.wthms.co/GLOM2E

Please, consider this bug report !

**Comment by juliaamosova** [comment] 2019-11-15 13:15
Thank you for raising this issue @keusta. 

I can reproduce this on any iPhone with iOS 12. However, the issue is fixed in iOS 13. Have you considered updating your phone to iOS 13? 

I am going to mark this issue as `bug` but given the fact that this issue is fixed in the latest version of iOS, we can't give it a `high` priority at this time.

**Comment by keusta** [comment] 2019-11-15 15:18
hey @juliaamosova thanks for reply

Iam not going to update for the moment.
Should be really quick to fix but im not geeky enough to understand how to (but i searched trust me)

**Comment by haszari** [comment] 2020-04-15 04:25
Is this bug still an issue? Some time has passed since iOS 13 was released - perhaps we can close this now.

By the way, I was not aware of this feature!  I'd appreciate it if anyone could paste a link to docs or info about Storefront's swipe/gesture support :)

**Comment by nerrad** [comment] 2020-07-13 15:50
I'm going to close this due to the age. If there are still issues with expected behaviour please do comment on this issue and we can consider reopening.

**Closed by nerrad** 2020-07-13 15:50 UTC
Labels: Priority: Low, Type: Bug
