### ISSUE TITLE
Question: Why hooks over templates?

### ISSUE THREAD

**Issue by fbm-static** [woocommerce/storefront#512] opened 2016-11-25 03:21 UTC
Just out of curiosity. I am checking popular themes and learning how they are coded and storefront seems to prefer the use of hooks instead of templates files. May I know why? Thank you so much.

**Comment by BurlesonBrad** [comment] 2016-11-25 05:34
Hooks let you customize custom customizations which are customizeable when you customize the customizations for a custom customer with customized customizations.

**Comment by jameskoster** [comment] 2016-11-25 10:50
The benefit of hooks and filters are that they are more specific and thus less potentially damaging.

If all the markup / logic is built directly in to the template, that means that changing even little things requires a full template override which can cause issues if there are template alterations in future releases.

There's also the added plus that we mimic how WooCommerce core handles templates, increasing familiarity between the codebases.

You don't necessarily _have_ to use hooks. All of the template tags in Storefront are pluggable so you have that option as well. It alls depends what you're planning to do :)

Make sense? 

PS closing this as it's not a bug report, feel free to continue the conversation though, if you have any other questions.

**Closed by jameskoster** 2016-11-25 10:50 UTC
