### ISSUE TITLE
unable to show more than 3 categories on homepage "shop by category" block - solved but really NOT

### ISSUE THREAD

**Issue by nciazone** [woocommerce/storefront#1293] opened 2020-03-16 18:44 UTC
## Describe the bug
this shows as a closed issued at https://github.com/woocommerce/storefront/issues/943
however i still cannot show more than 3 categories under the "shop by category" block on the homepage of storefront.
I have 6 categories and set the block as follows:

[product_categories limit="6" columns="6" orderby="menu_order"]

Isolating the problem (mark completed items with an [x]):
- [X ] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [X] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Go to 'homepage'
2. Scroll down to 'shop by category'
3. max 3 categories show (instead of 6)

## Expected behavior
show all 6 categories that have been set under products / categories

### Browser Environment
Firefox

- Platform: macOS
- Browser(s):
Firefox
### WordPress Environment
Please provide relevant details of your WordPress setup and server environment.
`
### WordPress Environment ###

WordPress address (URL): http://staging2.idiqfast.com
Site address (URL): http://staging2.idiqfast.com
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.15
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1d-fips

SUHOSIN Installed: –
MySQL Version: 5.7.25-28-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: ibb_
Total Database Size: 3.57MB
Database Data Size: 2.04MB
Database Index Size: 1.53MB
ibb_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ibb_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ibb_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
ibb_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
ibb_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_login_redirects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_options: Data: 0.30MB + Index: 0.06MB + Engine InnoDB
ibb_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
ibb_posts: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
ibb_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ibb_wcfm_daily_analysis: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_wcfm_detailed_analysis: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_enquiries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_enquiries_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_enquiries_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_enquiries_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_fbc_chat_rows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_fbc_chat_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_wcfm_fbc_chat_visitors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_fbc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_following_followers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_wcfm_marketplace_orders_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_product_multivendor: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_wcfm_marketplace_refund_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_refund_request_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_reverse_withdrawal: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_reverse_withdrawal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_reviews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_reviews_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_reviews_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_review_rating_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_store_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_vendor_ledger: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_withdraw_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_marketplace_withdraw_request_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_membership_subscription: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_wcfm_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_messages_modifier: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_messages_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_support: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_support_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_support_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wcfm_support_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ibb_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ibb_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ibb_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ibb_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
ibb_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ibb_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 16
customize_changeset: 18
nav_menu_item: 5
page: 12
post: 2
product: 14
revision: 47

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (7) ###

EditorsKit: by Jeffrey Carandang – 1.28
Peter's Login Redirect: by Peter Keung – 2.9.7
SG Optimizer: by SiteGround – 5.4.4
WCFM - WooCommerce Frontend Manager: by WC Lovers – 6.4.6
WCFM - WooCommerce Multivendor Marketplace: by WC Lovers – 3.3.6
WooCommerce: by Automattic – 4.0.0
WP-Members: by Chad Butler – 3.3.2.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #40 - /shop/
Cart: #41 - /cart/
Checkout: #42 - /checkout/
My account: #43 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2020-03-13 20:44:26 +0000
Newest: 2020-03-13 21:04:25 +0000

Pending: 1
Oldest: 2020-03-15 08:20:23 +0000
Newest: 2020-03-15 08:20:23 +0000

Canceled: 1
Oldest: -0001-11-30 00:00:00 +0000
Newest: -0001-11-30 00:00:00 +0000

```
</details>

**Comment by haszari** [comment] 2020-03-24 02:23
Hi @nciazone  – thanks for getting in touch. 

Can I confirm your setup details:

- You have more than 3 product categories set up in your store.
- You want to show more categories on the Storefront home page - e.g. six categories.

Is that correct?

I tried editing the `product_categories` shortcode in the home page, to show 6 product categories in my test site. After saving the page, the front end showed 6 categories. I'm using the WooCommerce sample product data, which has a few product categories set up.

<img width="733" alt="Screen Shot 2020-03-24 at 3 14 57 PM" src="https://user-images.githubusercontent.com/4167300/77381240-3bb55f00-6de2-11ea-919b-483a6643afb5.png">

<img width="1392" alt="Screen Shot 2020-03-24 at 3 11 09 PM" src="https://user-images.githubusercontent.com/4167300/77381248-3f48e600-6de2-11ea-9439-721b214c749d.png">

Could you take another look and ensure that you're editing the shortcode for the homepage, and you've saved (published) the changes? If it's still not working please comment with more details so we can figure this out.

Do all of your product categories have products? If a category is empty, or products are out of stock, it won't be displayed.

**Comment by nerrad** [comment] 2020-07-17 18:40
I'm going to close this issue because there hasn't been a reply in nearly 4 months. Feel free to add a comment if the issue is still happening. We will consider reopening then.

**Closed by nerrad** 2020-07-17 18:40 UTC
Labels: Status: Needs Author Feedback
