### ISSUE TITLE
3-column gallery - 3rd image not expanding on mobile

### ISSUE THREAD

**Issue by opicron** [woocommerce/storefront#1235] opened 2019-12-17 08:27 UTC
## Describe the bug
When using an three column gallery the 3rd image is not filling the available width on mobile responsive (in posts, not in woocommerce product content).

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
Create post
Add 3-column gallery
View on mobile

## Expected behavior
I expected the post(!) content block gallery 3rd image to expand to full width as in the woocommerce product content area which is actually working. It seems the gutenberg-blocks.css in intervering with this behaviour.

**Comment by opicron** [comment] 2019-12-17 08:34
I can actually fix this by commenting out the following code on [/assets/css/base/gutenberg-blocks.css] line 407:
```

.hentry .entry-content .wp-block-gallery .blocks-gallery-image, .hentry .entry-content .wp-block-gallery .blocks-gallery-item, .editor-styles-wrapper .wp-block-gallery .blocks-gallery-image, .editor-styles-wrapper .wp-block-gallery .blocks-gallery-item {
    width: 47.8260869565%;
    margin: 0 4.347826087% 4.347826087% 0;
    -webkit-box-flex: 0;
    -webkit-flex-grow: 0;
    flex-grow: 0;
}
```

**Comment by haszari** [comment] 2020-01-15 02:11
Hi there @opicron – thanks for reporting this. 

Can you add a screenshot to demonstrate the issue? I've tested locally and haven't reproduced the problem.

Here's what I see in Chrome responsive mode:

<img width="502" alt="Screen Shot 2020-01-15 at 3 09 57 PM" src="https://user-images.githubusercontent.com/4167300/72398806-1afcd780-37a9-11ea-9481-332cbbb1613a.png">

<img width="624" alt="Screen Shot 2020-01-15 at 3 09 27 PM" src="https://user-images.githubusercontent.com/4167300/72398822-23551280-37a9-11ea-8e10-a0e74aeea07e.png">

**Comment by opicron** [comment] 2020-01-19 13:52
Staging site (with incorrect 3rd image size):
https://www.tseportal.site/2019/12/18/de-sirui-w-2204-in-zijn-geliefde-terrein/

Production site (with commented css code):
https://www.tseportal.nl/2019/12/18/de-sirui-w-2204-in-zijn-geliefde-terrein/

**Comment by haszari** [comment] 2020-01-19 19:39
Thanks for clarifying that @opicron. Here's a screenshot of your site showing the issue:

<img width="695" alt="Screen Shot 2020-01-20 at 8 28 28 AM" src="https://user-images.githubusercontent.com/4167300/72687006-e305e380-3b5e-11ea-8565-b6ed8d8b7373.png">

However, I still can't reproduce the issue locally, even using the same images from your site. In my test, the third image is the same size as the others – it doesn't expand to full width.

<img width="643" alt="Screen Shot 2020-01-20 at 8 36 37 AM" src="https://user-images.githubusercontent.com/4167300/72687150-041b0400-3b60-11ea-861d-e848986309f5.png">

Can you share more details of how you've set up this gallery block? Is it possible there's other styling or css on your site which is causing the issue? 

If you can reproduce this using a basic site using only Storefront and WooCommerce with no other plugins or customisation, that would be helpful.

**Comment by opicron** [comment] 2020-01-19 22:43
Thanks for testing, what you are describing is exactly the issue. The third image should stretch to full with right? Somehow storefront css is blocking default gutenberg post css.

I think I left some code on the staging area which made the difference, but your description is spot on.

**Comment by haszari** [comment] 2020-05-13 03:43
Adding this to 2.5.7, assuming that we can safely fix this so core galleries work consistently in Storefront and other themes.

If for some reason this behaviour is intended by Storefront - i.e. this is by design – or if it's risky / complex to fix, we may close this issue until we get more feedback that it's causing problems for stores (instead of fixing it).

**Comment by haszari** [comment] 2020-05-19 01:28
I wanted to check to see if this is a new issue (introduced/regression) or is existing behaviour in Storefront. I tested with Storefront 2.5.0 and I saw the same behaviour:

<img width="1007" alt="Screen Shot 2020-05-19 at 1 26 17 PM" src="https://user-images.githubusercontent.com/4167300/82274464-5405bc80-99d4-11ea-9db8-b421c0830f4e.png">

Personally I like the idea of changing this to be more consistent with the core gallery behaviour, so any "dangling" image columns expand to full width. However, since this is a change in behaviour, we need to take care - existing sites may prefer the existing Storefront behaviour.

**Comment by opicron** [comment] 2020-05-26 11:34
Maybe make the default behaviour as current and add an customizer option to the theme? I detest the customizer and have a feeling the customizer might not live a long live but at least it is an viable solution.

**Comment by GlennMartin1** [comment] 2020-05-26 12:50
There are use cases where a large pic on the bottom row is really a poor idea. For example, I use the gallery block for displaying many small color swatches. It makes little/no sense to see the final pic as a huge one.

In other use cases, it's very nice, i.e. like in the [comment above](https://github.com/woocommerce/storefront/issues/1235#issuecomment-576038915) of scenery pics.

I'd say this should be an option on the gallery block settings. Each instance of the gallery block could have its own selection.

Keep the default to match present behavior so there's no unexpected results.

**Comment by opicron** [comment] 2020-05-26 16:01
@GlennMartin1 block option would be even better. Supplemented with an global setting maybe?

**Comment by nielslange** [comment] 2020-09-19 04:27
@haszari You marked this issue with `Priority: High` and `Type: Bug`. I just compared the behaviour of Storefront with the behaviour of the WordPress default themes.

<table>
<tr>
<td>Storefront:
<br><br>

![#1235-storefront](https://user-images.githubusercontent.com/3323310/93658801-058f2a00-fa69-11ea-902e-fba2e59293f3.png)
</td>
<td>Twenty Twenty:
<br><br>

![#1235-twenty-twenty](https://user-images.githubusercontent.com/3323310/93658825-3a02e600-fa69-11ea-8a87-7981ffebcee5.png)
</td>
<td>Twenty Nineteen:
<br><br>

![#1235-twenty-nineteen](https://user-images.githubusercontent.com/3323310/93658829-42f3b780-fa69-11ea-99e0-a9c1549a4f9a.png)
</td>
<td>Twenty Seventeen:
<br><br>

![#1235-twenty-seventeen](https://user-images.githubusercontent.com/3323310/93658831-48510200-fa69-11ea-9eb1-440ccecf3e12.png)
</td>
</tr>
</table>

<table>
<tr>
<td>Twenty Sixteen:
<br><br>

![#1235-twenty-sixteen](https://user-images.githubusercontent.com/3323310/93658904-05435e80-fa6a-11ea-8cf3-a9e1c8e46d36.png)
</td>
<td>Twenty Fifteen:
<br><br>

![#1235-twenty-fifteen](https://user-images.githubusercontent.com/3323310/93658907-08d6e580-fa6a-11ea-8efe-f19e36e46f6a.png)
</td>
<td>Twenty Fourteen:
<br><br>

![#1235-twenty-fourteen](https://user-images.githubusercontent.com/3323310/93658912-0c6a6c80-fa6a-11ea-9493-b40e34ee0e06.png)
</td>
<td>Twenty Thirteen:
<br><br>

![#1235-twenty-thirteen](https://user-images.githubusercontent.com/3323310/93658914-10968a00-fa6a-11ea-999d-921e997e99f7.png)
</td>
</tr>
</table>

<table>
<tr>
<td width="25%">Twenty Twelve:
<br><br>

![#1235-twenty-twelve](https://user-images.githubusercontent.com/3323310/93658884-c6ada400-fa69-11ea-93ce-4cfdd46db3cb.png)
</td>
<td width="25%">Twenty Eleven:
<br><br>

![#1235-twenty-eleven](https://user-images.githubusercontent.com/3323310/93658881-c3b2b380-fa69-11ea-9c9d-4eb2622bfec4.png)
</td>
<td width="25%">Twenty Ten:
<br><br>

![#1235-twenty-ten](https://user-images.githubusercontent.com/3323310/93658880-c01f2c80-fa69-11ea-9f62-8a3a634b2bcc.png)
</td>
<td width="25%"></td>
</tr>
</table>

Technically, the Storefront behaviour is not in sync with the behaviour of the WordPress default stores. That said, I do understand the point that @GlennMartin1 raised in https://github.com/woocommerce/storefront/issues/1235#issuecomment-634004201. The original bug as demonstrated by you in https://github.com/woocommerce/storefront/issues/1235#issuecomment-576038915 seems no longer to exist. I suggest closing this ticket and keep the functionality as it is at the moment. If users should be ale to select whether the last image on mobile should be full-with or left aligned, the gallery block should be adjusted accordingly. This should not be done by theStorefront theme. What are your thoughts on this?

cc: @jconroy, @Aljullu, @senadir, @nerrad

**Comment by haszari** [comment] 2020-09-21 00:33
> Technically, the Storefront behaviour is not in sync with the behaviour of the WordPress default stores.

Yes. Note – how galleries are rendered is arguably theme dependent, i.e. a theme can decide how images in galleries should be positioned/laid out. So although Storefront is different, it's arguably not "wrong", and possibly by design.

> I suggest closing this ticket and keep the functionality as it is at the moment.

That makes sense to me – we haven't had lots of reports of this issue affecting stores. We can always open a new issue if this becomes a higher priority or impacts more stores.

Closing!

**Closed by haszari** 2020-09-21 00:33 UTC
Labels: Priority: High, Status: has-pr, Type: Bug

**Comment by opicron** [comment] 2020-09-23 20:09
Gutenberg defaults behaviour is stretch on mobile. Its not theme dependent at all in the basic sense if you approach it from Gutenberg. I find it odd that the Gutenberg CSS is being overriden in this case.
