### ISSUE TITLE
Search field on mobile only appears after three taps

### ISSUE THREAD

**Issue by stephhjacq** [woocommerce/storefront#1145] opened 2019-05-24 20:25 UTC
Ticket: 2058293-zen

On mobile, tapping the button to search appears to do nothing. Only on the third tap does the field appear. Customers don't try more than once, so think it's broken.

To reproduce:

Scroll page so menu bars retract
Tap search button once:

![https://cld.wthms.co/2NiLYc](https://cld.wthms.co/2NiLYc+)
Full Image: https://cld.wthms.co/2NiLYc+

Tap search button second time, browser nav appears but no search field:
![https://cld.wthms.co/kPWgbR](https://cld.wthms.co/kPWgbR+)
Full Image: https://cld.wthms.co/kPWgbR+

Tap third time, field appears:
![https://cld.wthms.co/tJOzzY](https://cld.wthms.co/tJOzzY+)
Full Image: https://cld.wthms.co/tJOzzY+

**Comment by ben72** [comment] 2019-05-25 16:45
I could reproduce this. But after updating my iPhone6 I get the search field on the second tap. On the first I get the browser nav.

**Comment by tiagonoronha** [comment] 2019-05-29 15:30
I spent sometime researching the issue - https://www.eventbrite.com/engineering/mobile-safari-why/

**Comment by stephhjacq** [comment] 2019-05-29 15:35
Wow, thanks @tiagonoronha. Does that mean we'd consider this something we won't/can't fix, or would we consider a complex solution as mentioned in the article?

**Comment by tiagonoronha** [comment] 2019-05-29 15:44
@stephhjacq We'll probably end up having to come up with a similar solution as EventBrite.

**Comment by haszari** [comment] 2020-05-13 03:40
Adding to 2.5.7 so we can close this issue. 

Ideally we find a safe fix and ship it 🚢 

If this is out of our control and is essentially an iOS / Mobile Safari known issue, let's confirm the details and close the issue.

**Comment by jconroy** [comment] 2020-05-18 11:22
I'm still seeing the 2 (or 3) tap issue (depending on whether I've just scrolled or the browser toolbar is is/is not shown). If the page is _still_ and toolbar is shown it generally it works first time.

[I was trying to see is this article is related but ran out of time](https://css-tricks.com/annoying-mobile-double-tap-link-issue/).

**Comment by haszari** [comment] 2020-05-18 20:59
> If the page is still and toolbar is shown it generally it works first time.

That sounds fine to me, perhaps we can close this. 

> I was trying to see is this article is related but ran out of time. https://css-tricks.com/annoying-mobile-double-tap-link-issue/

I don't think that's relevant - that issue is related to hyperlinks showing the hover state on first tap ("special" iOS behaviour). I don't think our search icon has a hover state.

I just tested myself and this seems to be appropriate iOS behaviour, where the real web UI has different layers depending on what's happening (as you noted in your testing).

- When scrolling, tapping will stop the scroll. This makes sense to me - you need a way to stop scroll without accidentally clicking a link.
- When the browser menu / address bar is hidden, tapping will reveal the address bar (top) and toolbar (bottom). Again, it makes sense that this tap is intercepted to prevent accidental clicks.

I couldn't find apple docs for this behaviour, but here are a few articles related:

- https://www.eventbrite.com/engineering/mobile-safari-why/
- https://www.lifewire.com/using-safari-iphone-browser-2000784
- https://www.idownloadblog.com/2016/01/19/tip-show-safari-toolbar-on-ios-without-having-to-scroll-back-up/

Based on this, I think we can safely close this as expected behaviour. If we get more reports about it perhaps we can take another look.

**Closed by haszari** 2020-05-18 20:59 UTC
Labels: Priority: High, Type: Bug

**Comment by jconroy** [comment] 2020-05-18 22:43
> I don't think that's relevant - that issue is related to hyperlinks showing the hover state on first tap ("special" iOS behaviour). I don't think our search icon has a hover state.

Fair enough. I was going to check if [hover state like this one](https://github.com/woocommerce/storefront/blob/master/assets/css/base/_base.scss#L462) would be playing any part.

> I think we can safely close this as expected behaviour. If we get more reports about it perhaps we can take another look.

I think that is a fair call.
