### ISSUE TITLE
Core stylesheet overriding customizer settings

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#523] opened 2016-12-09 10:57 UTC
Ticket: 501729-zd-woothemes

When selecting a footer background color under **Appearance > Customize > Footer > Background Color**, the color is saving correctly, although the base stylesheet of Storefront is *more specific* than the styles generated by Customizer (Screenshot at: http://cld.wthms.co/Yg9h/24KebALs).

The reason for this is that:

* SF Stylesheet uses `background-color`; AND
* Customizer uses `background`

With `background-color` being more specific than `background` when using the same classnames, it's clear that the SF stylesheet will always "win" the specificity race.

I Propose either changing Customizer's to ```background-color``` OR using the ```#colophon``` ID selector instead (with ID's trumping classnames).

**Comment by jameskoster** [comment] 2016-12-09 13:53
Hm, I'm not seeing this. Here's what I see;

![footer](https://cldup.com/fsahkqG3rA-3000x3000.png)

Both the stylesheet and the inline css are targeting `.site-footer` and using `background-color`.

* [Evidence 1](https://github.com/woocommerce/storefront/blob/master/inc/customizer/class-storefront-customizer.php#L642).
* [Evidence 2](https://github.com/woocommerce/storefront/blob/master/assets/sass/base/_base.scss#L383)

But now I'm wondering how this happened. I suspect it's something to do with how they're loading CSS in their child theme. First step of course is to ask them to switch to core and see if the issue persists. Just to confirm it _is_ the child theme.

I just tested with a blank child theme and the setting works fine. So I really need to see how they're loading CSS, or if they've changed anything in the Customizer to diagnose further.

Remember Storefront automatically loads child themes style.css file in the correct order. So if they're doing this in the child theme as well that's likely the cause of the issue.

Going to close this out, but please let me know if you manage to solve the issue. Of course if switching to core doesn't resolve and it looks like an issue in Storefront please re-open.

**Closed by jameskoster** 2016-12-09 13:53 UTC
Labels: [Priority] Normal, [Type] Bug

**Comment by allendav** [comment] 2016-12-14 21:34
I also could not reproduce this either, however, looking closer at the merchant's store reveals that the storefront stylesheet is being loaded twice - with the second load happening after customizer styles are embedded - and this is why the footer color changes are being ignored.

<img width="979" alt="instances" src="https://cloud.githubusercontent.com/assets/1595739/21202016/f7244502-c201-11e6-9fac-9957bab38c58.png">

<img width="600" alt="network" src="https://cloud.githubusercontent.com/assets/1595739/21202018/fe2237e2-c201-11e6-95d5-53f343d5f369.png">

As there is no stylesheet reference at the line indicated by the network debugging view, I suspect javascript in a plugin is injecting the style sheet the second time.

I've asked the merchant to disable each plugin on the site, in turn, to see if the custom colors appear when a given plugin is disabled.

**Comment by jameskoster** [comment] 2016-12-15 13:04
@allendav did you try this;

> First step of course is to ask them to switch to core and see if the issue persists. Just to confirm it is the child theme.

? 

I'm 99% sure it'll be their child theme causing this.
