### ISSUE TITLE
[BUG] Fatal error when WooCommerce Admin is disabled (again)

### ISSUE THREAD

**Issue by ospiotr** [woocommerce/storefront#1623] opened 2021-03-07 23:39 UTC
Hey there!

**Describe the bug**

I am using an [official WooCommerce filter](https://woocommerce.wp-a2z.org/oik_hook/woocommerce_admin_disabled/) to disable WooCommerce Admin in my site:
`add_filter( 'woocommerce_admin_disabled', '__return_true' );`

When Storefront is trying to display a notice), fatal error happens:

```
Fatal error:  Uncaught Exception: Invalid data store. in /wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct()
#1 /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Note.php(87): WC_Data_Store::load()
#2 /wp-content/themes/storefront/inc/nux/class-storefront-nux-admin-inbox-messages-customize.php(32): Automattic\WooCommerce\Admin\Notes\Note->__construct()
#3 /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/NoteTraits.php(74): Storefront_NUX_Admin_Inbox_Messages_Customize::get_note()
#4 /wp-content/themes/storefront/inc/nux/class-storefront-nux-admin.php(213): Storefront_NUX_Admin_Inbox_Messages_Customize::possibly_add_note()
#5 /wp-includes/class-wp-hook.php(287): Storefront_NUX_Admin->admin_inbox_mess in /wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 107
```

There was a similar problem in Storefront 3.0.0:  #1566. It's the same situation again.

**Solution**

It seems that Storefront is not correctly checking if WooCommerce Admin is activated. It is trying to display the WooCommerce Admin notice without checking if it is possible.

There is a WooCommerce function for this: **[is_wc_admin_active](https://woocommerce.wp-a2z.org/oik_api/woocommerceis_wc_admin_active/)**

**To Reproduce**
1. Use fresh WooCommerce installation
2. Apply the filter `add_filter( 'woocommerce_admin_disabled', '__return_true' );`
3. Make sure that WooCommerce Status shows WooCommerce Admin as `Inactive`
4. Activate Storefront
5. Fatal error

**Operating environment:**
- Storefront  version: 3.5.0
- WooCommerce version: 5.0.0
- WordPress version: 5.6.2
- PHP version: 7.4.15

**Comment by opr** [comment] 2021-03-09 15:56
Hi thanks for reporting this to us, I've just tried reproducing using the same software versions that you've listed, but I was not able to.

When I activate storefront on a fresh site with WooCommerce Admin disabled via a filter, I still see the "Design your store 🎨" notice without any errors.

I also asked one of my teammates @Aljullu to attempt to reproduce this and he was also unable.

On the basis that we can't reproduce this, I'll close this issue, but if you have any further instructions or relevant information that can help us reproduce, please feel free to reopen it and we'll investigate further.

You may find additional debugging information here https://docs.woocommerce.com/document/woocommerce-self-service-guide/ which could help you find more information as to what's causing this on your side.

**Comment by adrianduffell** [comment] 2021-06-21 12:32
I ran into this issue testing WC Admin with Storefront. To reproduce, I think the filter in step 2 needs to be applied early before WC Admin initializes. I was using the following mu-plugin:

**wp-content/mu-plugins/disable-wc-admin.php:**
```php
<?php

add_filter( 'woocommerce_admin_disabled', '__return_true' );
```

**Comment by adrianduffell** [comment] 2021-06-21 12:58
Apologies, on closer inspection it was another plugin generating the error 😅

**Closed as completed by adrianduffell** 2021-06-21 12:58 UTC
