### ISSUE TITLE
Second page infinite scroll shows the first page results

### ISSUE THREAD

**Issue by Khrol** [woocommerce/storefront#1063] opened 2019-02-19 13:47 UTC
How to reproduce:
1. Open https://signed.one/fr/shop/
2. Scroll to the end of the product list (https://signed.one/fr/shop/page/2/).
Actual result:
Last items are the same as the first products.
Expected:
All products are listed. If https://signed.one/fr/shop/page/2/ is reloaded, correct items from the second page are shown.

Video: https://cloudup.com/cKCcWwYnsBc
ZD # 1814684

Notes:
1. The issue wasn't reproduced on the clean setup.
2. If extra third-party plugins are deactivated by the user, the issue is still in place.

**Comment by seanconklin** [comment] 2019-03-04 21:15
I have reproduced this issue with the latest Storefront theme, WooCommerce, and JetPack.

Instead of reloading the page the user clicks into a product then clicks the BACK button on their browser to see the lower results (not the original category page).

Example URL: https://jinnybeyer.com/product-category/fabric/

Steps to reproduce:
- Scroll down past Palette number 12 so it loads more results.
- Click Palette number 14.
- Click BACK button on browser.
- Notice if you scroll up the top product is Palette number 13, not all of the subcategories you see when you had first landed on the URL.

Note: Reproduced using Safari and FireFox browsers.
Note: This seems to be caused by the return URL containing `page/2/`

**Comment by tiagonoronha** [comment] 2019-03-05 15:01
@seanconklin that's the correct behaviour for Jetpack's Infinite Scroll. When you scroll down, it changes to a different page. When you click on a product and then go back you go to the default WordPress paginated page.

**Comment by seanconklin** [comment] 2019-03-05 17:24
Hi @tiagonoronha. Thanks for the update, and sorry if this may be a different underlying issue. I've opened this in a new ticket #1071 and will explain further inside there.

**Comment by tiagonoronha** [comment] 2019-03-07 18:40
Replied on the ZD ticket. Closing for now.

**Closed by tiagonoronha** 2019-03-07 18:40 UTC
